version: '3.8'
services:
  rentAcar: #container name
    image: postgres:14.1-alpine
    restart: always # docker host başladığında buda başlasın
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carRental
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/date # Datalrın kalıcı olmasını istiyorsan volumes verilmeli

volumes:
  db:
