spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5434/carRental
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      show-sql: 'true'
      ddl-auto: create
server:
  port: '8080'
